version: '3.8'

services:
  # Servicio de la base de datos MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      # Opcional: Expone el puerto a tu máquina local para usar un cliente como DBeaver
      - "3307:3306"

  # Servicio de la aplicación Django
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000   
    volumes:
      # Monta el código local dentro del contenedor para reflejar cambios al instante
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env # Carga las variables de entorno desde el archivo .env
    depends_on:
      - db # Asegura que el contenedor de la BD inicie antes que la app

volumes:
  mysql_data: